version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test143
      db_host: db
    ports:
      - 5432:5432
  app:
    build: .
    command: ["./GORest"]
    ports: 
      - "8080:8080"
    depends_on:
      - db
    links:
      - db